import json
from pathlib import Path

notebook_content = {
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# ARC Prize 2026 — ARC-AGI-2 Sovereign Solver Engine\n",
    "## Composed Shape-Aware Induction, D4 Dihedral Symmetry & Color Homomorphism Engine\n",
    "**Team:** Sovereign AGI Research | **Track:** ARC-AGI-2 ($700,000 USD Category)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import sys\n",
    "import json\n",
    "import glob\n",
    "import time\n",
    "from pathlib import Path\n",
    "from typing import Any, Dict, List, Optional, Set, Tuple\n",
    "import numpy as np\n",
    "\n",
    "print('[*] Initializing Sovereign ARC-AGI-2 High-Throughput Solver...')\n",
    "_MAX_DIM = 64\n",
    "\n",
    "def _to_grid(data: Any) -> Optional[np.ndarray]:\n",
    "    try:\n",
    "        if not isinstance(data, list) or not data or not isinstance(data[0], list):\n",
    "            return None\n",
    "        h, w = len(data), len(data[0])\n",
    "        if h == 0 or w == 0 or h > _MAX_DIM or w > _MAX_DIM:\n",
    "            return None\n",
    "        g = np.zeros((h, w), dtype=np.uint8)\n",
    "        for y, row in enumerate(data):\n",
    "            if not isinstance(row, list) or len(row) != w:\n",
    "                return None\n",
    "            for x, v in enumerate(row):\n",
    "                g[y, x] = max(0, min(15, int(v)))\n",
    "        return g\n",
    "    except Exception:\n",
    "        return None\n",
    "\n",
    "def _to_json(g: np.ndarray) -> List[List[int]]:\n",
    "    return [[int(v) for v in row] for row in g]\n",
    "\n",
    "# =========================================================================\n",
    "# 1. SHAPE-RULE INDUCTION\n",
    "# =========================================================================\n",
    "\n",
    "def _learn_shape_rule(pairs: List[Tuple[np.ndarray, np.ndarray]]) -> Tuple[str, Any]:\n",
    "    try:\n",
    "        if not pairs:\n",
    "            return 'unknown', None\n",
    "        if all(b.shape == a.shape for b, a in pairs):\n",
    "            return 'same', None\n",
    "        ratios: Set[Tuple[int, int]] = set()\n",
    "        is_tile = True\n",
    "        for b, a in pairs:\n",
    "            bh, bw = b.shape\n",
    "            ah, aw = a.shape\n",
    "            if ah % bh != 0 or aw % bw != 0:\n",
    "                is_tile = False\n",
    "                break\n",
    "            ratios.add((ah // bh, aw // bw))\n",
    "        if is_tile and len(ratios) == 1:\n",
    "            return 'tile', ratios.pop()\n",
    "        outs = {a.shape for _, a in pairs}\n",
    "        if len(outs) == 1:\n",
    "            return 'fixed', outs.pop()\n",
    "        scalings: Set[Tuple[float, float]] = set()\n",
    "        for b, a in pairs:\n",
    "            bh, bw = b.shape\n",
    "            ah, aw = a.shape\n",
    "            scalings.add((round(ah / bh, 3), round(aw / bw, 3)))\n",
    "        if len(scalings) == 1:\n",
    "            return 'resize', scalings.pop()\n",
    "        return 'unknown', None\n",
    "    except Exception:\n",
    "        return 'unknown', None\n",
    "\n",
    "def _apply_shape(rule: str, params: Any, tin: np.ndarray) -> Optional[np.ndarray]:\n",
    "    try:\n",
    "        if rule == 'same':\n",
    "            return tin.copy()\n",
    "        if rule == 'tile':\n",
    "            kh, kw = params\n",
    "            oh, ow = tin.shape[0] * kh, tin.shape[1] * kw\n",
    "            if oh <= _MAX_DIM and ow <= _MAX_DIM:\n",
    "                return np.tile(tin, (kh, kw))\n",
    "            return None\n",
    "        if rule == 'resize':\n",
    "            ry, rx = params\n",
    "            oh, ow = int(round(tin.shape[0] * ry)), int(round(tin.shape[1] * rx))\n",
    "            if 1 <= oh <= _MAX_DIM and 1 <= ow <= _MAX_DIM:\n",
    "                ys = (np.arange(oh) / ry).astype(int)\n",
    "                xs = (np.arange(ow) / rx).astype(int)\n",
    "                ys = np.clip(ys, 0, tin.shape[0] - 1)\n",
    "                xs = np.clip(xs, 0, tin.shape[1] - 1)\n",
    "                return tin[np.ix_(ys, xs)]\n",
    "            return None\n",
    "        if rule == 'fixed':\n",
    "            oh, ow = params\n",
    "            if oh <= 0 or ow <= 0 or oh > _MAX_DIM or ow > _MAX_DIM:\n",
    "                return None\n",
    "            if oh <= tin.shape[0] and ow <= tin.shape[1]:\n",
    "                return tin[:oh, :ow]\n",
    "            out = np.zeros((oh, ow), dtype=np.uint8)\n",
    "            h, w = min(oh, tin.shape[0]), min(ow, tin.shape[1])\n",
    "            out[:h, :w] = tin[:h, :w]\n",
    "            return out\n",
    "        return None\n",
    "    except Exception:\n",
    "        return None\n",
    "\n",
    "def _learn_crop_offset(pairs: List[Tuple[np.ndarray, np.ndarray]], oh: int, ow: int) -> Optional[Tuple[int, int]]:\n",
    "    try:\n",
    "        offsets: Set[Tuple[int, int]] = set()\n",
    "        for b, a in pairs:\n",
    "            bh, bw = b.shape\n",
    "            if oh > bh or ow > bw:\n",
    "                return None\n",
    "            found = None\n",
    "            for y in range(bh - oh + 1):\n",
    "                for x in range(bw - ow + 1):\n",
    "                    if np.array_equal(b[y:y + oh, x:x + ow], a):\n",
    "                        found = (y, x)\n",
    "                        break\n",
    "                if found is not None:\n",
    "                    break\n",
    "            if found is None:\n",
    "                return None\n",
    "            offsets.add(found)\n",
    "        if len(offsets) == 1:\n",
    "            return offsets.pop()\n",
    "        return None\n",
    "    except Exception:\n",
    "        return None\n",
    "\n",
    "# =========================================================================\n",
    "# 2. D4 DIHEDRAL GROUP & COLOR HOMOMORPHISM\n",
    "# =========================================================================\n",
    "\n",
    "D4_OPERATIONS = [\n",
    "    'identity',\n",
    "    'rot90',\n",
    "    'rot180',\n",
    "    'rot270',\n",
    "    'flip_h',\n",
    "    'flip_v',\n",
    "    'transpose',\n",
    "    'anti_transpose',\n",
    "]\n",
    "\n",
    "def _apply_d4(g: np.ndarray, op: str) -> np.ndarray:\n",
    "    if op == 'identity':\n",
    "        return g\n",
    "    elif op == 'rot90':\n",
    "        return np.rot90(g, -1)\n",
    "    elif op == 'rot180':\n",
    "        return np.rot90(g, 2)\n",
    "    elif op == 'rot270':\n",
    "        return np.rot90(g, 1)\n",
    "    elif op == 'flip_h':\n",
    "        return np.fliplr(g)\n",
    "    elif op == 'flip_v':\n",
    "        return np.flipud(g)\n",
    "    elif op == 'transpose':\n",
    "        return g.T\n",
    "    elif op == 'anti_transpose':\n",
    "        return np.rot90(np.fliplr(g), 1)\n",
    "    return g\n",
    "\n",
    "def _learn_color_map(pairs: List[Tuple[np.ndarray, np.ndarray]]) -> Optional[Tuple[int, ...]]:\n",
    "    try:\n",
    "        lut = list(range(16))\n",
    "        for b, a in pairs:\n",
    "            if b.shape != a.shape:\n",
    "                return None\n",
    "            for bv, av in zip(b.ravel(), a.ravel()):\n",
    "                ibv, iav = int(bv), int(av)\n",
    "                if lut[ibv] != ibv and lut[ibv] != iav:\n",
    "                    return None\n",
    "                lut[ibv] = iav\n",
    "        return tuple(lut)\n",
    "    except Exception:\n",
    "        return None\n",
    "\n",
    "def _apply_color_map(g: np.ndarray, lut_tuple: Tuple[int, ...]) -> np.ndarray:\n",
    "    lut = np.array(lut_tuple, dtype=np.uint8)\n",
    "    return lut[g]\n",
    "\n",
    "# =========================================================================\n",
    "# 3. SOLVE TASK\n",
    "# =========================================================================\n",
    "\n",
    "def solve_task(train_pairs: List[Tuple[Any, Any]], test_input: Any) -> List[List[List[int]]]:\n",
    "    tin = _to_grid(test_input)\n",
    "    if tin is None:\n",
    "        return [[[0]], [[0]]]\n",
    "    pairs: List[Tuple[np.ndarray, np.ndarray]] = []\n",
    "    for before, after in train_pairs:\n",
    "        b, a = _to_grid(before), _to_grid(after)\n",
    "        if b is not None and a is not None:\n",
    "            pairs.append((b, a))\n",
    "    if not pairs:\n",
    "        return [_to_json(tin), _to_json(tin)]\n",
    "    attempts: List[np.ndarray] = []\n",
    "    rule, params = _learn_shape_rule(pairs)\n",
    "    for d4_op in D4_OPERATIONS:\n",
    "        transformed_pairs = []\n",
    "        possible = True\n",
    "        for b, a in pairs:\n",
    "            shaped = _apply_shape(rule, params, b)\n",
    "            if shaped is None:\n",
    "                possible = False\n",
    "                break\n",
    "            geo = _apply_d4(shaped, d4_op)\n",
    "            if geo.shape != a.shape:\n",
    "                possible = False\n",
    "                break\n",
    "            transformed_pairs.append((geo, a))\n",
    "        if possible and transformed_pairs:\n",
    "            cmap = _learn_color_map(transformed_pairs)\n",
    "            if cmap is not None:\n",
    "                shaped_test = _apply_shape(rule, params, tin)\n",
    "                if shaped_test is not None:\n",
    "                    geo_test = _apply_d4(shaped_test, d4_op)\n",
    "                    out = _apply_color_map(geo_test, cmap)\n",
    "                    attempts.append(out)\n",
    "                    break\n",
    "    if not attempts and rule == 'fixed':\n",
    "        oh, ow = params\n",
    "        off = _learn_crop_offset(pairs, oh, ow)\n",
    "        if off is not None:\n",
    "            y, x = off\n",
    "            if y + oh <= tin.shape[0] and x + ow <= tin.shape[1]:\n",
    "                attempts.append(tin[y:y + oh, x:x + ow])\n",
    "    if not attempts:\n",
    "        shaped = _apply_shape(rule, params, tin)\n",
    "        attempts.append(shaped if shaped is not None else tin.copy())\n",
    "    if len(attempts) < 2:\n",
    "        alt = np.fliplr(attempts[0])\n",
    "        attempts.append(alt if not np.array_equal(alt, attempts[0]) else attempts[0])\n",
    "    else:\n",
    "        attempts = attempts[:2]\n",
    "    return [_to_json(attempts[0]), _to_json(attempts[1])]\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# =========================================================================\n",
    "# 4. MAIN INFERENCE EXECUTION & SUBMISSION PARQUET/JSON EMISSION\n",
    "# =========================================================================\n",
    "\n",
    "def find_challenges_file():\n",
    "    candidates = [\n",
    "        '/kaggle/input/arc-prize-2026-arc-agi-2/arc-agi_test_challenges.json',\n",
    "        '/kaggle/input/competitions/arc-prize-2026-arc-agi-2/arc-agi_test_challenges.json',\n",
    "        '/kaggle/input/arc-prize-2026-arc-agi-2/arc-agi_evaluation_challenges.json',\n",
    "        '/kaggle/input/competitions/arc-prize-2026-arc-agi-2/arc-agi_evaluation_challenges.json',\n",
    "        'arc-agi_test_challenges.json',\n",
    "    ]\n",
    "    for c in candidates:\n",
    "        if Path(c).is_file():\n",
    "            return Path(c)\n",
    "    matches = glob.glob('/kaggle/input/**/*challenges.json', recursive=True)\n",
    "    return Path(matches[0]) if matches else Path(candidates[0])\n",
    "\n",
    "challenges_path = find_challenges_file()\n",
    "print(f'[*] Reading challenges from: {challenges_path}')\n",
    "\n",
    "if challenges_path.is_file():\n",
    "    with open(challenges_path, 'r', encoding='utf-8') as f:\n",
    "        tasks = json.load(f)\n",
    "else:\n",
    "    tasks = {}\n",
    "\n",
    "submission = {}\n",
    "t0 = time.time()\n",
    "print(f'[*] Solving {len(tasks)} tasks...')\n",
    "\n",
    "for task_id, task_data in tasks.items():\n",
    "    train_pairs = [(ex['input'], ex['output']) for ex in task_data.get('train', [])]\n",
    "    test_cases = task_data.get('test', [])\n",
    "    task_sub = []\n",
    "    for test_idx, test_case in enumerate(test_cases):\n",
    "        test_in = test_case.get('input', [[0]])\n",
    "        attempts = solve_task(train_pairs, test_in)\n",
    "        task_sub.append({\n",
    "            'attempt_1': attempts[0],\n",
    "            'attempt_2': attempts[1]\n",
    "        })\n",
    "    submission[task_id] = task_sub\n",
    "\n",
    "elapsed = time.time() - t0\n",
    "print(f'[+] Solved {len(submission)} tasks in {elapsed:.2f}s ({len(submission)/(elapsed+1e-5):.1f} tasks/sec)')\n",
    "\n",
    "sub_path = Path('submission.json')\n",
    "with open(sub_path, 'w', encoding='utf-8') as f:\n",
    "    json.dump(submission, f)\n",
    "\n",
    "print(f'[+] submission.json created successfully ({sub_path.stat().st_size} bytes).')\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.1"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}

with open(r'starter_push_agi2\vibe-xi-omega-arc2.ipynb', 'w', encoding='utf-8') as f:
    json.dump(notebook_content, f, indent=1)

print('ARC-AGI-2 submission notebook created successfully!')
